"""Rename CVProfile to Profile and add photo_filename

Revision ID: 7e93130661f1
Revises: 
Create Date: 2025-09-14 02:30:16.554757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e93130661f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('cv_profiles', 'profiles')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('photo_filename')

    op.rename_table('profiles', 'cv_profiles')
    # ### end Alembic commands ###
